const CONFIG = {

  OWM_KEY: 'a93bfd738c3a2ff7c6b0a80b5d5c0c9d',

  AMADEUS_API_KEY:    'YOUR_AMADEUS_API_KEY_HERE',
  AMADEUS_API_SECRET: 'YOUR_AMADEUS_API_SECRET_HERE',
  AMADEUS_BASE_URL:   'https://test.api.amadeus.com',

  YOUTUBE_KEY: 'YOUR_YOUTUBE_API_KEY_HERE',

  WEATHER_UNITS: 'metric',
  MAX_FLIGHT_RESULTS: 5,
  MAX_VIDEO_RESULTS: 3,
  DEFAULT_ORIGIN_AIRPORT: 'DUB', 

  ENABLE_FLIGHTS: true,
  ENABLE_VIDEOS:  true,
  ENABLE_MAP:     true,
};
